# Generado automaticamente - NO EDITAR MANUALMENTE
# Microservicio: nexus-ms-geografia
# Namespace: nexus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-ms-geografia
  namespace: nexus
  labels:
    app: nexus-ms-geografia
    bank: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-ms-geografia
  template:
    metadata:
      labels:
        app: nexus-ms-geografia
        bank: nexus
    spec:
      containers:
        - name: nexus-ms-geografia
          image: 851112555783.dkr.ecr.us-east-2.amazonaws.com/nexus-ms-geografia:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: nexus-db-credentials
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nexus-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexus-db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-ms-geografia
  namespace: nexus
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nexus-ms-geografia