# GitHub Actions: Deploy to EKS
# Copiar a: .github/workflows/deploy.yml en cada repo de banco
name: Build and Deploy to EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-2
  EKS_CLUSTER: eks-banca-ecosistema
  # MODIFICAR SEGÚN TU BANCO:
  NAMESPACE: arcbank                   # arcbank | bantec | nexus | ecusol | switch
  ECR_REPO: arcbank-service-clientes   # Nombre del repo ECR
  SERVICE_NAME: service-clientes       # Nombre del deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      
      - name: Build and push image
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPO }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPO }}:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/${{ env.ECR_REPO }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
      
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/${{ env.SERVICE_NAME }} \
            ${{ env.SERVICE_NAME }}=${{ steps.build.outputs.image }} \
            -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.SERVICE_NAME }} -n ${{ env.NAMESPACE }} --timeout=300s
