apiVersion: apps/v1
kind: Deployment
metadata:
  name: switch-ms-contabilidad
  namespace: switch
  labels:
    app: switch-ms-contabilidad
    bank: switch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: switch-ms-contabilidad
  template:
    metadata:
      labels:
        app: switch-ms-contabilidad
        bank: switch
    spec:
      containers:
        - name: switch-ms-contabilidad
          image: 851112555783.dkr.ecr.us-east-2.amazonaws.com/switch-ms-contabilidad:251793239cbc75b3d07923b372e1ae8d978c0043
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: switch-db-credentials
                  key: contabilidad-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: switch-db-credentials
                  key: contabilidad-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: switch-db-credentials
                  key: contabilidad-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: switch-ms-contabilidad
  namespace: switch
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: switch-ms-contabilidad