# Generado automaticamente - NO EDITAR MANUALMENTE
# Microservicio: switch-ms-directorio
# Namespace: switch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: switch-ms-directorio
  namespace: switch
  labels:
    app: switch-ms-directorio
    bank: switch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: switch-ms-directorio
  template:
    metadata:
      labels:
        app: switch-ms-directorio
        bank: switch
    spec:
      containers:
        - name: switch-ms-directorio
          image: 851112555783.dkr.ecr.us-east-2.amazonaws.com/switch-ms-directorio:7bfc973103164637ce57489d43e3fd088d5eeb34
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: AWS_REGION
              value: "us-east-2"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: switch-ms-directorio
  namespace: switch
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: switch-ms-directorio