# Microservicio: service-cuentas (PostgreSQL)
# Namespace: arcbank | Puerto: 8081
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-cuentas
  namespace: arcbank
  labels:
    app: service-cuentas
    bank: arcbank
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-cuentas
  template:
    metadata:
      labels:
        app: service-cuentas
        bank: arcbank
    spec:
      containers:
        - name: service-cuentas
          image: 851112555783.dkr.ecr.us-east-2.amazonaws.com/arcbank-service-cuentas:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: arcbank-db-credentials
                  key: cuentas-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: arcbank-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arcbank-db-credentials
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service-cuentas
  namespace: arcbank
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: service-cuentas